# Generated by Django 6.1 on 2026-09-04 06:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nif', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='NominaMensual',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.IntegerField()),
                ('mes', models.IntegerField()),
                ('departamento', models.CharField(max_length=100)),
                ('deveng', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_din', models.DecimalField(decimal_places=2, max_digits=10)),
                ('base_esp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('irpf_esp', models.DecimalField(decimal_places=2, max_digits=10)),
                ('irpf_din', models.DecimalField(decimal_places=2, max_digits=10)),
                ('embarg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('prima', models.DecimalField(decimal_places=2, max_digits=10)),
                ('manut', models.DecimalField(decimal_places=2, max_digits=10)),
                ('enf_acc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('bonif', models.DecimalField(decimal_places=2, max_digits=10)),
                ('s_neto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ss_trabaj', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ss_empr', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rlc', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_tot', models.DecimalField(decimal_places=2, max_digits=10)),
                ('importe_extra', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominas', to='nominas.empleado')),
            ],
            options={
                'ordering': ['-anio', '-mes', 'empleado__nombre'],
                'unique_together': {('empleado', 'anio', 'mes')},
            },
        ),
    ]
