# Generated by Django 6.1 on 2026-09-29 06:30

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField(unique=True, verbose_name='año')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('cerrado', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'ejercicio',
                'verbose_name_plural': 'ejercicios',
                'ordering': ['-anio'],
            },
        ),
        migrations.CreateModel(
            name='CuentaContable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=12, unique=True, verbose_name='código')),
                ('nombre', models.CharField(max_length=200)),
                ('imputable', models.BooleanField(default=True, help_text='Si admite apuntes directos (las cuentas agrupadoras no).')),
                ('activa', models.BooleanField(default=True)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='hijas', to='cuadro_cuentas.cuentacontable')),
            ],
            options={
                'verbose_name': 'cuenta contable',
                'verbose_name_plural': 'cuentas contables',
                'ordering': ['codigo'],
            },
        ),
        migrations.CreateModel(
            name='Asiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(blank=True, null=True, verbose_name='número')),
                ('fecha', models.DateField()),
                ('concepto', models.CharField(max_length=255)),
                ('origen', models.CharField(choices=[('manual', 'Manual'), ('albaranes', 'Albaranes'), ('facturas', 'Facturas'), ('nominas', 'Nóminas'), ('banco', 'Banco')], default='manual', max_length=20)),
                ('referencia_origen', models.CharField(blank=True, help_text="Identificador del documento de origen (p. ej. 'albaran:123').", max_length=100)),
                ('estado', models.CharField(choices=[('borrador', 'Borrador'), ('contabilizado', 'Contabilizado')], default='borrador', max_length=20)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('ejercicio', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='asientos', to='cuadro_cuentas.ejercicio')),
            ],
            options={
                'verbose_name': 'asiento',
                'verbose_name_plural': 'asientos',
                'ordering': ['-fecha', '-numero'],
            },
        ),
        migrations.CreateModel(
            name='Apunte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.PositiveSmallIntegerField(default=0)),
                ('concepto', models.CharField(blank=True, max_length=255)),
                ('debe', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('haber', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=14)),
                ('departamento', models.CharField(blank=True, choices=[('cocina', 'Cocina'), ('recepcion', 'Recepción'), ('comedor', 'Comedor'), ('mantenimiento', 'Mantenimiento'), ('lavanderia', 'Lavandería')], max_length=20)),
                ('asiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apuntes', to='cuadro_cuentas.asiento')),
                ('contrapartida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='cuadro_cuentas.cuentacontable')),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='apuntes', to='cuadro_cuentas.cuentacontable')),
            ],
            options={
                'verbose_name': 'apunte',
                'verbose_name_plural': 'apuntes',
                'ordering': ['asiento', 'orden', 'id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('debe__gt', 0), ('haber', 0)), models.Q(('debe', 0), ('haber__gt', 0)), _connector='OR'), name='apunte_debe_o_haber')],
            },
        ),
        migrations.AddConstraint(
            model_name='asiento',
            constraint=models.UniqueConstraint(fields=('ejercicio', 'numero'), name='asiento_numero_unico_por_ejercicio'),
        ),
    ]
