# Generated by Django 6.1.1 on 2026-10-02 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadro_cuentas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuentacontable',
            name='definicion',
            field=models.TextField(blank=True, verbose_name='definición'),
        ),
        migrations.AddField(
            model_name='cuentacontable',
            name='nif',
            field=models.CharField(blank=True, max_length=20, verbose_name='NIF/CIF'),
        ),
        migrations.AddField(
            model_name='cuentacontable',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=300, verbose_name='ubicación en el balance'),
        ),
    ]
