# Generated by Django 6.1.1 on 2026-10-02 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadro_cuentas', '0002_cuentacontable_definicion_cuentacontable_nif_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asiento',
            name='modelo',
            field=models.CharField(blank=True, help_text='Asiento modelo con el que se generó.', max_length=40),
        ),
        migrations.AddField(
            model_name='asiento',
            name='tipo',
            field=models.CharField(choices=[('apertura', 'Apertura'), ('operacion', 'Operación'), ('ajuste', 'Ajuste'), ('regularizacion', 'Regularización'), ('cierre', 'Cierre')], default='operacion', max_length=20),
        ),
        migrations.AlterField(
            model_name='asiento',
            name='referencia_origen',
            field=models.CharField(blank=True, help_text="Documento de origen (nº de factura, 'albaran:123'...).", max_length=100),
        ),
    ]
