# Generated by Django 6.1.1 on 2026-10-05 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuadro_cuentas', '0003_asiento_tipo_modelo'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('denominacion', models.CharField(max_length=200, verbose_name='denominación social')),
                ('nif', models.CharField(blank=True, max_length=20, verbose_name='NIF')),
                ('forma_juridica', models.CharField(blank=True, help_text='Sociedad limitada, sociedad anónima, comunidad de bienes...', max_length=100, verbose_name='forma jurídica')),
                ('domicilio', models.CharField(blank=True, max_length=255)),
                ('actividad', models.CharField(blank=True, help_text='Por ejemplo: explotación hotelera.', max_length=255)),
            ],
            options={
                'verbose_name': 'datos de la empresa',
                'verbose_name_plural': 'datos de la empresa',
            },
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='fecha_formulacion',
            field=models.DateField(blank=True, help_text='Fecha en que se formulan las cuentas anuales (como máximo, tres meses tras el cierre).', null=True, verbose_name='fecha de formulación'),
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='trabajadores_medios',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Para saber si se pueden presentar cuentas anuales abreviadas (norma 4ª).', max_digits=7, null=True, verbose_name='número medio de trabajadores'),
        ),
    ]
