# Generated by Django 6.1.1 on 2026-10-05 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuadro_cuentas', '0004_cuentas_anuales'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apunte',
            name='departamento',
        ),
    ]
