# Generated by Django 6.1.1 on 2026-09-28 20:48

import django.db.models.deletion
import invoice_data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=invoice_data.models.invoice_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('checksum', models.CharField(help_text='SHA-256 del contenido: evita importar dos veces el mismo archivo.', max_length=64, unique=True)),
                ('tipo_entidad', models.CharField(choices=[('proveedor', 'Proveedor'), ('acreedor', 'Acreedor')], default='proveedor', max_length=20)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('source_path', models.CharField(blank=True, help_text='Ruta original desde la que se importó (auditoría).', max_length=1000)),
                ('source_type', models.CharField(choices=[('digital_pdf', 'PDF digital (con capa de texto)'), ('scanned_pdf', 'PDF escaneado (solo imagen)'), ('image', 'Imagen (foto o escaneo suelto)'), ('unknown', 'Desconocido')], default='unknown', max_length=20)),
                ('page_count', models.PositiveIntegerField(default=1)),
                ('needs_ocr', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ingested', 'Ingerido'), ('needs_ocr', 'Pendiente de OCR'), ('preprocessed', 'Preprocesado (listo para OCR)'), ('ocr_done', 'OCR completado'), ('error', 'Error'), ('duplicate', 'Duplicado (ya existia)')], default='ingested', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('raw_text_layer', models.TextField(blank=True, help_text='Capa de texto de PDFs digitales (vacío en escaneos/imágenes).')),
                ('ocr_text', models.TextField(blank=True, help_text='Texto por OCR de página completa (solo escaneos/imágenes).')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cif', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=200)),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'proveedores',
                'ordering': ['nombre', 'cif'],
            },
        ),
        migrations.CreateModel(
            name='ExtractedInvoiceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(blank=True, max_length=100)),
                ('fecha_factura', models.DateField(blank=True, null=True)),
                ('fecha_texto', models.CharField(blank=True, help_text='La fecha tal como está impresa.', max_length=30)),
                ('proveedor_nombre', models.CharField(blank=True, max_length=200)),
                ('proveedor_cif', models.CharField(blank=True, max_length=20)),
                ('base_imponible', models.DecimalField(blank=True, decimal_places=2, help_text='Total sin IVA.', max_digits=12, null=True)),
                ('iva_total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, help_text='Total con IVA.', max_digits=12, null=True)),
                ('cuadra', models.BooleanField(default=False, help_text='Las líneas cuadran con el bloque de impuestos y el total.')),
                ('metodo', models.CharField(blank=True, max_length=40)),
                ('estado', models.CharField(choices=[('ok', 'Correcta'), ('revisar', 'Necesita revisión')], default='revisar', max_length=10)),
                ('verificacion', models.JSONField(blank=True, default=dict)),
                ('motor_version', models.CharField(blank=True, max_length=30)),
                ('confirmado', models.BooleanField(default=False, help_text='Revisada y aceptada por una persona.')),
                ('corregido', models.BooleanField(default=False, help_text='Se modificó a mano algún campo tras la extracción.')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='datos', to='invoice_data.invoicedocument')),
            ],
            options={
                'verbose_name': 'datos de factura',
                'verbose_name_plural': 'datos de facturas',
            },
        ),
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_articulo', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=500)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('iva_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('albaran', models.CharField(blank=True, max_length=100)),
                ('albaran_fecha', models.DateField(blank=True, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas', to='invoice_data.invoicedocument')),
            ],
            options={
                'verbose_name': 'línea de factura',
                'verbose_name_plural': 'líneas de factura',
                'ordering': ['document', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceTaxBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.DecimalField(decimal_places=2, help_text='Tipo de IVA en %.', max_digits=5)),
                ('base', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cuota', models.DecimalField(decimal_places=2, max_digits=12)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='impuestos', to='invoice_data.invoicedocument')),
            ],
            options={
                'verbose_name': 'desglose de IVA',
                'verbose_name_plural': 'desgloses de IVA',
                'ordering': ['document', '-tipo'],
            },
        ),
        migrations.AddField(
            model_name='invoicedocument',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documentos', to='invoice_data.proveedor'),
        ),
        migrations.CreateModel(
            name='InvoicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('processed_image', models.ImageField(upload_to=invoice_data.models.invoice_page_upload_path)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='invoice_data.invoicedocument')),
            ],
            options={
                'ordering': ['document', 'page_number'],
                'unique_together': {('document', 'page_number')},
            },
        ),
    ]
