# Generated by Django 6.1 on 2026-09-15 13:06

import django.db.models.deletion
import invoice_data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedocument',
            name='ocr_text',
            field=models.TextField(blank=True, help_text='Texto extraido por OCR para documentos escaneados/imagenes (vacio para PDFs digitales).'),
        ),
        migrations.CreateModel(
            name='InvoicePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.PositiveIntegerField()),
                ('processed_image', models.ImageField(upload_to=invoice_data.models.invoice_page_upload_path)),
                ('width', models.PositiveIntegerField(default=0)),
                ('height', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='invoice_data.invoicedocument')),
            ],
            options={
                'ordering': ['document', 'page_number'],
                'unique_together': {('document', 'page_number')},
            },
        ),
    ]
