# Generated by Django 6.1 on 2026-09-15 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_data', '0002_invoicedocument_ocr_text_invoicepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtractedInvoiceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_factura', models.DateField(blank=True, null=True)),
                ('proveedor_cif', models.CharField(blank=True, max_length=20, null=True)),
                ('base_imponible', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('iva_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('total', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('extracted', 'Extraido correctamente'), ('needs_review', 'Necesita revision manual')], default='needs_review', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='extracted_data', to='invoice_data.invoicedocument')),
            ],
        ),
    ]
