# Generated by Django 6.1 on 2026-09-16 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_data', '0004_extractedinvoicedata_extraction_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceLineItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_articulo', models.CharField(blank=True, max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('iva_porcentaje', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('cantidad', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('precio_unitario', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('importe', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='invoice_data.invoicedocument')),
            ],
            options={
                'ordering': ['document', 'id'],
            },
        ),
    ]
