# Generated by Django 6.1 on 2026-09-16 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_data', '0005_invoicelineitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedinvoicedata',
            name='confirmado',
            field=models.BooleanField(default=False, help_text='Si el usuario ha revisado y aceptado estos datos como correctos.'),
        ),
        migrations.AddField(
            model_name='invoicelineitem',
            name='confirmado',
            field=models.BooleanField(default=False),
        ),
    ]
