# Generated by Django 6.1 on 2026-09-05 07:50

import invoice_data.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=500, upload_to=invoice_data.models.invoice_upload_path)),
                ('original_filename', models.CharField(max_length=255)),
                ('checksum', models.CharField(help_text='SHA-256 of the file contents, used to avoid re-importing the same file twice.', max_length=64, unique=True)),
                ('departamento', models.CharField(blank=True, max_length=100)),
                ('source_path', models.CharField(blank=True, help_text='Original path this file was ingested from, kept for audit purposes.', max_length=1000)),
                ('source_type', models.CharField(choices=[('digital_pdf', 'PDF digital (con capa de texto)'), ('scanned_pdf', 'PDF escaneado (solo imagen)'), ('image', 'Imagen (foto o escaneo suelto)'), ('unknown', 'Desconocido')], default='unknown', max_length=20)),
                ('page_count', models.PositiveIntegerField(default=1)),
                ('needs_ocr', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('ingested', 'Ingerido'), ('needs_ocr', 'Pendiente de OCR'), ('error', 'Error'), ('duplicate', 'Duplicado (ya existia)')], default='ingested', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('raw_text_layer', models.TextField(blank=True, help_text='Extracted text layer for digital PDFs (empty for scans/images).')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-imported_at'],
            },
        ),
    ]
