# Generated by Django 6.1 on 2026-09-15 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_data', '0003_extractedinvoicedata'),
    ]

    operations = [
        migrations.AddField(
            model_name='extractedinvoicedata',
            name='extraction_method',
            field=models.CharField(blank=True, help_text='Que metodo genero estos datos: invoice2data_template, regex_fallback, etc.', max_length=30),
        ),
    ]
