# Generated by Django 6.1 on 2026-09-16 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoice_data', '0006_extractedinvoicedata_confirmado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoicedocument',
            name='tipo_entidad',
            field=models.CharField(choices=[('proveedor', 'Proveedor'), ('acreedor', 'Acreedor')], default='proveedor', max_length=20),
        ),
        migrations.AlterField(
            model_name='invoicedocument',
            name='status',
            field=models.CharField(choices=[('ingested', 'Ingerido'), ('needs_ocr', 'Pendiente de OCR'), ('preprocessed', 'Preprocesado (listo para OCR)'), ('ocr_done', 'OCR completado'), ('error', 'Error'), ('duplicate', 'Duplicado (ya existia)')], default='ingested', max_length=20),
        ),
    ]
